[tool.black]
line-length = 100
target-version = ['py312']
extend-exclude = "alembic"

[tool.pylint."messages control"]
ignore = ["setup.py", "__init__.py", "alembic"]
disable = "all"
enable = [
  "empty-docstring",
  "missing-class-docstring",
  "missing-function-docstring",
  "missing-module-docstring"
]

[tool.isort]
profile = "black"
known_first_party = ["rmatzke"]
