name: build-publish
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      repository-name:
        required: true
        type: string
      image-name:
        required: true
        type: string
jobs:
  build-publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      tagged_image_url: ${{ steps.build-image.outputs.tagged_image_url }}
    env:
      IMAGE_URL: ${{ vars.CLOUD_REGISTRY_URL }}/${{ vars.GCP_PROJECT_ID }}/${{ inputs.repository-name }}/${{ inputs.image-name }}
      IMAGE_TAG: ${GITHUB_SHA::8}
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v4
      - name: 'GCloud Authentication'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.CLOUD_REGISTRY_SERVICE_ACCOUNT_CREDS }}
      - name: 'Setup GCloud CLI'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'
      - name: 'Build Image'
        id: build-image
        run: |
          docker build \
          -t ${{ env.IMAGE_URL }}:latest \
          -t ${{ env.IMAGE_URL }}:${{ env.IMAGE_TAG }} \
          -f ${{ inputs.dockerfile }} \
          .
          echo "tagged_image_url=${{ env.IMAGE_URL }}:${{ env.IMAGE_TAG }}" >> "$GITHUB_OUTPUT"
          echo $tagged_image_url
        shell: bash
      - name: 'Push Image to Cloud Artifact Registry'
        run: |
          gcloud auth configure-docker ${{ vars.CLOUD_REGISTRY_URL }}
          docker push ${{ env.IMAGE_URL }} --all-tags
        shell: bash
