name: build-data-collector
on:
  push:
    branches: [ 'main' ]
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: 'test'
  workflow_dispatch:
jobs:
  build-data-collector:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v4
      - name: 'GCloud Authentication'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.CLOUD_REGISTRY_SERVICE_ACCOUNT_CREDS }}
      - name: 'Setup GCloud CLI'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'
      - name: 'Test GCloud CLI'
        run: |
          gcloud info
        shell: bash
      - name: 'Build Image'
        run: |
          docker build \
          -t us-central1-docker.pkg.dev/csca-5028-final-project-455714/docker-test/data-collector:latest \
          -f applications/data-collector/Dockerfile \
          .
        shell: bash
#      - name: 'Push Image to Artifact Registry'
#        run: |
#          docker push us-central1-docker.pkg.dev/csca-5028-final-project-455714/docker-test/data-collector:latest
#        shell: bash
