name: build-publish-data-collector
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  build-publish-data-collector:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      CLOUD_REPO_NAME: docker-${{ inputs.environment }}
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v4
      - name: 'GCloud Authentication'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.CLOUD_REGISTRY_SERVICE_ACCOUNT_CREDS }}
      - name: 'Setup GCloud CLI'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'
      - name: 'Build Image'
        run: |
          docker build \
          -t ${{ vars.CLOUD_REGISTRY_URL }}/${{ vars.GCP_PROJECT_ID }}/${{ env.CLOUD_REPO_NAME }}/data-collector:latest \
          -f applications/data-collector/Dockerfile \
          .
        shell: bash
      - name: 'Push Image to Artifact Registry'
        run: |
          gcloud auth configure-docker ${{ vars.CLOUD_REGISTRY_URL }}
          docker push ${{ vars.CLOUD_REGISTRY_URL }}/${{ vars.GCP_PROJECT_ID }}/${{ env.CLOUD_REPO_NAME }}/data-collector:latest
        shell: bash
