name: build-publish
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      repository-name:
        required: true
        type: string
      image-name:
        required: true
        type: string
jobs:
  build-publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      IMAGE_NAME: ${{ vars.CLOUD_REGISTRY_URL }}/${{ vars.GCP_PROJECT_ID }}/${{ inputs.repository-name }}/${{ inputs.image-name }}
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v4
      - name: 'GCloud Authentication'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.CLOUD_REGISTRY_SERVICE_ACCOUNT_CREDS }}
      - name: 'Setup GCloud CLI'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'
      - name: 'Build Image'
        run: |
          docker build \
          -t ${{ env.IMAGE_NAME }}:latest \
          -t ${{ env.IMAGE_NAME }}:${GITHUB_SHA::8} \
          -f ${{ inputs.dockerfile }} \
          .
        shell: bash
      - name: 'Push Image to Cloud Artifact Registry'
        run: |
          gcloud auth configure-docker ${{ vars.CLOUD_REGISTRY_URL }}
          docker push ${{ env.IMAGE_NAME }} --all-tags
        shell: bash
