name: db-migration
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  db-migration:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v4
        with:
          sparse-checkout: databases
      - name: 'Cloud SQL Service Account Credentials'
        run: |
          cat << EOF > ./cloud-sql-creds.json
          ${{ secrets.CLOUD_SQL_SERVICE_ACCOUNT_CREDS }}
          EOF
        shell: bash
      - name: 'Cloud SQL Auth Proxy'
        run: |
          curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.15.2/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy
          ./cloud-sql-proxy --credentials-file cloud-sql-creds.json ${{ secrets.CLOUD_SQL_INSTANCE_NAME }} &
        shell: bash
      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: 'Install Dependencies'
        run: |
          cd databases/movie-recaps
          pip install -r requirements.txt
        shell: bash
      - name: 'Run Migration'
        env:
          DATABASE_URI: 'postgresql+psycopg2://${{ secrets.CLOUD_SQL_DB_USER }}:${{ secrets.CLOUD_SQL_DB_PASSWORD }}@127.0.0.1:5432/${{ secrets.CLOUD_SQL_DB_NAME }}'
        run: |
          cd databases/movie-recaps
          python migrate.py
        shell: bash
      - name: 'Summary'
        run: |
          echo """
            ### Database Migration
            - Migration Status: Success
            - Environment: ${{ inputs.environment }}          
          """ >> $GITHUB_STEP_SUMMARY
        shell: bash
