name: integration-tests
on:
  workflow_call:
jobs:
  db-migration:
    uses: ./.github/workflows/db-migration.yml
    secrets: inherit
    with:
      environment: test
  integration-tests:
    needs: [ db-migration ]
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v4
      - name: 'Cloud SQL Service Account Credentials'
        run: |
          cat << EOF > ./cloud-sql-creds.json
          ${{ secrets.CLOUD_SQL_SERVICE_ACCOUNT_CREDS }}
          EOF
        shell: bash
      - name: 'Cloud SQL Auth Proxy'
        run: |
          curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.15.2/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy
          ./cloud-sql-proxy --credentials-file cloud-sql-creds.json ${{ secrets.CLOUD_SQL_INSTANCE_NAME }} &
        shell: bash
      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: 'Install Dependencies'
        run: |
          cd components
          pip install -r requirements.txt
        shell: bash
      - name: 'Run Tests'
        env:
          TEST_DATABASE_URI: 'postgresql+psycopg2://${{ secrets.CLOUD_SQL_DB_USER }}:${{ secrets.CLOUD_SQL_DB_PASSWORD }}@127.0.0.1:5432/${{ secrets.CLOUD_SQL_DB_NAME }}'
        run: |
          cd components
          coverage run -m unittest discover
          COVERAGE_REPORT=$(coverage report -m)
          echo """
            ```
            $COVERAGE_REPORT
            ```
          """ >> $GITHUB_STEP_SUMMARY
        shell: bash
