name: main
on:
  push:
    branches: ['main']
  workflow_dispatch:
jobs:
  run-db-migration:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v3
        with:
          sparse-checkout: databases
      - name: 'Get Service Account Credentials'
        run: |
          cat << EOF > ./sa-creds.json
          ${{ secrets.GCP_SA_DB_CREDS }}
          EOF
        shell: bash
      - name: 'Setup Cloud SQL Auth Proxy'
        run: |
          curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.15.2/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy
          ./cloud-sql-proxy --credentials-file sa-creds.json ${{ secrets.GCP_DB_INSTANCE }} &
        shell: bash
      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: 'Install Dependencies'
        run: |
          cd databases/movie-recaps
          pip install -r requirements.txt
        shell: bash
      - name: 'Run Migration'
        env:
          DATABASE_URI: 'postgresql+psycopg2://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@127.0.0.1:5432/${{ secrets.DB_NAME }}'
        run: |
          echo $DATABASE_URI
          cd databases/movie-recaps
          python migrate.py
        shell: bash
