name: main
on:
  workflow_dispatch:
jobs:
  run-db-migration:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v3
        with:
          sparse-checkout: databases
      - name: 'Start Cloud SQL Auth Proxy'
        uses: mattes/gce-cloudsql-proxy-action@v1
        with:
          creds: ${{ secrets.GCP_SA_DB_CREDS }}
          instance: ${{ secrets.GCP_DB_INSTANCE }}
      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: 'Run Migration'
        run: |
          ls
          echo "Test"
#          cd movie-recaps
#          pip install -r requirements.txt
#          python migrate.py
        shell: bash
        env:
          DATABASE_URI: 'postgresql+psycopg2://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}'
