name: main
on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:
jobs:
  db-migration-test:
    uses: ./.github/workflows/db-migration.yml
    secrets: inherit
    with:
      environment: test
  integration-tests:
    needs: [ db-migration-test ]
    uses: ./.github/workflows/integration-tests.yml
    secrets: inherit
  db-migration-dev:
    needs: [ integration-tests ]
    uses: ./.github/workflows/db-migration.yml
    secrets: inherit
    with:
      environment: dev
  build-publish-data-collector-dev:
    needs: [ db-migration-dev ]
    uses: ./.github/workflows/build-publish-data-collector.yml
    permissions:
      contents: 'read'
      id-token: 'write'
    secrets: inherit
    with:
      environment: dev
