name: main
run-name: main
on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:
jobs:
  db-migration:
    uses: ./.github/workflows/db-migration.yml
    with:
      environment: test
  run-tests:
    runs-on: ubuntu-latest
    needs: [ db-migration ]
    uses: ./.github/workflows/integration-tests.yml
    with:
      environment: test
