name: main
on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:
jobs:
  db-migration:
    uses: ./.github/workflows/db-migration.yml
    secrets: inherit
    with:
      environment: test
  integration-tests:
    needs: [ db-migration ]
    uses: ./.github/workflows/integration-tests.yml
    secrets: inherit
