name: web-ui
on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:
jobs:
  web-ui-build:
    uses: ./.github/workflows/build-publish.yml
    permissions:
      contents: 'read'
      id-token: 'write'
    secrets: inherit
    with:
      environment: dev
      dockerfile: applications/web-ui/Dockerfile
      repository-name: docker-dev
      image-name: web-ui
      build-args: --build-arg NEXT_PUBLIC_API_URL="${{ vars.REST_API_URL }}"
